spring:
  social:
    twitter:
      appId: mxsGonBL83TVN11yjKS9Q
      appSecret: WrqFsVdaGkT89VmLT2xvFSrQNyE0lq2CuSjyxiEI7c
      auto-connection-views: true
  redis:
    host: localhost
    port: 6379
    password: null
    database: 0
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
security:
  basic:
    enabled: false
